### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SweetGFX** [dtzxporter/ModmeWiki#15]
seem to have an issue whenever I try to extract a "pilot_medium or heavy" model/animation. Tried to extract rampart model but kept crashing, was able to extract heirloom animations.

**Comment by nighthawk333** [comment]
Same. Either everyone has a secret fix or we are the only ones with the issue hmm

**Comment by jazzar-dev** [comment]
you can use legion+. https://github.com/r-ex/LegionPlus/releases/tag/1.4.0 @SweetGFX
