### ISSUE TITLE
Crashing on extraction

### ISSUE THREAD

**Issue by nighthawk333** [dtzxporter/ModmeWiki#16]
Tried extracting a character model after the latest Apex Legends update and it now crashed for all models i try. Any solution? Any cause?

**Comment by SweetGFX** [comment]
I actually stumbled across DTZ's twitter and as of December 2021, he retracted the update for Legion and is no longer interested in coding it, so that may be the reason it's not working properly. "Good bye forever" he tweeted on his tweet regarding the retraction

**Comment by nighthawk333** [comment]
:(

**Comment by jazzar-dev** [comment]
you can use legion+. https://github.com/r-ex/LegionPlus/releases/tag/1.4.0 @xxxhushxx @nighthawk333
