### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by najdGG** [dtzxporter/ModmeWiki#17]
Legion - The Apex Legends
everytime i try export a model or anything else the app crashed.
and many thing else make the app crash

**Comment by SweetGFX** [comment]
I actually stumbled across DTZ's twitter and as of December 2021, he retracted the update for Legion and is no longer interested in coding it, so that may be the reason it's not working properly. "Good bye forever" he tweeted on his tweet regarding the retraction

**Comment by najdGG** [comment]
> I actually stumbled across DTZ's twitter and as of December 2021, he retracted the update for Legion and is no longer interested in coding it, so that may be the reason it's not working properly. "Good bye forever" he tweeted on his tweet regarding the retraction

sad :\
Is there an alternative to this program ؟

**Comment by Chazzr** [comment]
@xxxhushxx Thanks for sharing what you can. Looks like you discord link is now invalid. Would you happen to have a working link?

**Comment by Chazzr** [comment]
@xxxhushxx actually nm I found that someone is developing [LegionPlus](https://github.com/r-ex/LegionPlus). Their latest release fixed all the crash issues. I hope this helps yall. :)

**Comment by jazzar-dev** [comment]
you can use legion+. https://github.com/r-ex/LegionPlus/releases/tag/1.4.0
