### ISSUE TITLE
Making discord to share files we have since the recent crash

### ISSUE THREAD

**Issue by xxxhushxx** [dtzxporter/ModmeWiki#18]
lets make a file sharing I'm sure if we pool together we can keep most of the files open to use. 

i have alot of the base weapons files but was in the middle of a project when this happened.. tring to use r5reloaded to grab files from....

https://discord.gg/7ybkEmrt

**Comment by Sycix-HK** [comment]
@xxxhushxx Is the discord still alive? Can I get a link?

**Comment by jazzar-dev** [comment]
for anyone who wants to do it you can use legion+. https://github.com/r-ex/LegionPlus/releases/tag/1.4.0
